name: YouFaceIt CI/CD

on:
 pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
       - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: npm i

  deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js [14.16.0]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/projects/youfaceit
            git checkout .
            git pull
            npm install
            pm2 restart youfaceit --update-env